apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-configmap
  namespace: evaluation-service
  labels:
    app: evaluation-service
data:
  REDIS_URL: "redis://evaluation-service.4tvrl7.0001.use1.cache.amazonaws.com:6379"
  FLAG_SERVICE_URL: "http://flag-service-clusterip.flag-service.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service-clusterip.targeting-service.svc.cluster.local:8003"
  SERVICE_API_KEY: #
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/123945314948/minhafila"
