apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-configmap
  namespace: evaluation-service
  labels:
    app: evaluation-service
data:
  REDIS_URL: #
  FLAG_SERVICE_URL: #
  TARGETING_SERVICE_URL: #
  SERVICE_API_KEY: #
  AWS_REGION: #
  AWS_SQS_URL: #
