apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: evaluation-service
type: Opaque
data:
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMTIzOTQ1MzE0OTQ4L21pbmhhZmlsYQ==
  AWS_REGION: dXMtZWFzdC0x
  AWS_ACCESS_KEY_ID: QVNJQVJaVzVYTktDUFJHUENaN0U=
  AWS_SECRET_ACCESS_KEY: eVJaUzlaYUZzLzZrSDZKVjJsaXJWSC9LMUdyT0lURFI0alNjRFpmMA==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVBQWFDWFZ6TFhkbGMzUXRNaUpITUVVQ0lCd2NWVktCbXBoYTNBWjVTbzdya1NwZ0ExYllFL25Bd1E0clk4Mjh4UVpiQWlFQWphb3o4Y2dzMUpjY245cVRsSC9TSHhQajFkOHk2NEpTL01oOThicjI5ZDBxdlFJSXlmLy8vLy8vLy8vL0FSQUFHZ3d4TWpNNU5EVXpNVFE1TkRnaURPeFNrQ2VOeGFYdE1qUmhpeXFSQXBrcmU1L1dNeE9qejl0VXdSTjZRaG9PdGtObWxvelZJckw1M2VVUE1DQWhweWZOeEdMMGZxRy9kS1VYUDdxK0I3OUFpdGpvQ0ZZRlp0ek5QcUpoWm90R2ZvQngrMXhyNDZVa3ZDR2FCa2dSQnU2eDZ4S1RxbEttQXgzNm9TZ3I1dFkxVFBCVnpsSEhta3NwcEp4WVV5eFFBZFBKd3NYK1NWWldLV01PdlRpVndYakFRVFRCd1BiaFgyYW9ra2pub1NFUm5LWFVQZXptVG5XQkVOTDNBd0toS1NkWmtIMFkxT3E1M2xvQkhoTWVDVWUxVktoWkFhWWJuTXI0MUhUaFdFOERucTVpeU9SWXFoZHFPMUQxUjB5ckpEQ21Ia0d2ei96enJpejlrYU5vNmtwYWxsVzBhT2daVUtXdkZNVGhROUp4VlFla24xUDY0TE40eTdSVUNubnNGQU9ZTjRvSHptVjRseXd2Q1hqTTREQ2N4NjdRQmpxZEFWQU9ta1ZEMmVZUldrRkV2T2l1eVVTbkdFMVc0VFR5QTc3RTBwUDJPQnRzeWpEOWJTTVZtTjNXZVJYdTJhRTZnOGpQOXBoTitiUXdGZHlrQkpUQ0dqRjMreXpycmpob3ZwSHRwazJ3N25EU1dIczh5RHpIZ1dKOTJZNksxREhlbitlQ081cFYvU2RSbDhVcXhjMVJTdGdhRWdmNzhtZjFkWEdzSE1VUHgrUzZKa2dsakczRWZkZGdMNEtnbXFkTUZHQ3dDWlhwdUxDZDlNSERUZWc9