apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: evaluation-service
type: Opaque
data:
   AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMTIzOTQ1MzE0OTQ4L21pbmhhZmlsYQ==
   AWS_REGION: dXMtZWFzdC0x
   AWS_ACCESS_KEY_ID: QVNJQVJaVzVYTktDTFQ3WVJNWTY=
   AWS_SECRET_ACCESS_KEY: dWNXZ1p6V3lrTlprOFBlRkx1VHZxREt2d0RsMnpqMU9IUHRkV01oRA==
   AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVHRWFDWFZ6TFhkbGMzUXRNaUpJTUVZQ0lRRFhrQ3g3ZDJRVGM0ZGliYU1LbTAveW5nRlM4ZnppNVFXOC9DOVBtYUxDUHdJaEFOYmxjSlJ4ZjM3TENYSGRqNzBjMUZPR2VXNTh1VDVjekFQbkhyS2lVM0syS3JRQ0NDb1FBQm9NTVRJek9UUTFNekUwT1RRNElnekFsTGVNNzB1d1VKdld0eW9xa1FMcXczNlZ4Q1l3TUZ5OGhKN3dMRjNzSUdURTI0QWpENldGdC9aY3BtTDZwVlJMNDNxYmNKNGYyVHkwbzJLUkY5VFJETjZ4SVhRUWpXbUltVzRZUzUrTDBGQU5LRGF1d1ZCNWVoeitLRlhSeFg0TzV3WDluUjVuaGl0RGRjQTI1YmhEQ0lZeURoa2dpNitKWUVoaUJVMWg4WDRQckRqVkNUTUdpZjhXYi8yYitwYnNPVmcwSHlyYVFiNis5dkhMNXhqaS8xcDJ2aDlXK1VnS1pqbm50WDFMekVaOUFwZml5TzYvMDRkU0NoYXQ2M1FsQUlzS1hwN0I0ZUpHVUFuMmNQT3d1cFpQUFBHRFRWc3YrVGpWQ0Z4MUM2TW1CM2ZRalFiNm56QWV5ZUdSOWNHanJWNG02L3NrUWpVTXAyM1Jrci9lbElwbGJWNWRmUVhDRzRaZGpGMER3VnJKcGI3b2p2UVdKQk92OXJQQUNrRXczZkREMEFZNm5BSEFlVEFlYW96ckhDaEhBb09qeWZxNmExb2JZem1VNGV5dzA0L1NvNVRlajM3MmZqUTVkYmp3bE8zTVNpSXlsdzZLUjk5VVRodWl3TDI5Y0hJMEtzei9Tc3BvQ1BGK0N4eWduTnFybG5Uc29VQ1JLd3RjZDhnYjZhV3prSUZyYmhSdG9UNld3djRuUlVrNm1DRFdjK3F3VzNlSmlkOXB1K3l3M2pPOUtHR1paZmFVWHljTEUvMmFFMGdxRnVRMHVYbDA0MFRPL1pmYlNEUHpjN1k9