apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: evaluation-service
type: Opaque
data:
   AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMTIzOTQ1MzE0OTQ4L21pbmhhZmlsYQ==
   AWS_REGION: dXMtZWFzdC0x
   AWS_ACCESS_KEY_ID: QVNJQVc2VDU1VUNYV1lBSjJVN1o=
   AWS_SECRET_ACCESS_KEY: aW1YVWxyNnNteWRWMG8yTVhONk91VGZHa001aW9QdHhnVHpTUGNnRg==
   AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVLYi8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpJTUVZQ0lRQ0FSUE1WYXNsYUx4VmFzK3UwTDhCUi9jeE9tNTVMT3V6R1J6WWMvMTd3SVFJaEFKWmtwOUEwWXNLZVlJdlFYdDBOTkk1T3N3bFlzZ2ZIVkdnWDY5ZEdzdFJ0S3JJQ0NHOFFBaG9NTkRjNE1EYzVNVGszTXpVNUlneW1CNVpza0poeitpSkp1YThxandKTUNxU1hJZ0tGd2IvMUZGb1NFZHVCK1lOVDgxQTducE9pbGU5OUhyYXcwTjF1NGxtcFl2dFlucmJmMVY1VUFmK3diTUxSWW5iTnFlU1VpTVVUMEwvdnRHNEN6cDBoNGJwc3FEUWNiTTNxdjdIMzdDT2ZqbFUxb0lTT1hYa2hZQlU1aUxyZ1NFdHpYM3ZXcmtLRVJMK2JEa2lrbEYySWc1UzRGTEMwZE8rL21UY21IMHdSNDVZa1JQbEFybHZOdnFJNGRnTUdLc3lrSG5UZjRwTTFvcmN1MFpKNG9qZTUxU1hiZXpLTy8waXlBZWxzNGNvTmxleWMvTzFlVzdtVTF2bCtZRk9RUzlzb0tpbHdWNS9iVFRVZE1BYTRCcmhGZGlHM3hDNmdKOU53TGFCY2ZDei9wY08zeDg4WE0zY0VuS3lKMnhlaWVuNGlkbnAvRnJEQ3pyK2t3Tk9wQkk3VGpVKzkzVjJqVDl5dU1QK08wOUFHT3B3QlN6S1hMdTF5NTY3VEk2MVppdHV3SlVmdjNHYnFGOVJ1OStycmoranpqb2NQVkpFcFVOYm5SN1NqMm9LWEJFcHZNdzFsSWY2MWRqK0lPdmRqVmlPL3YzelpwMWc0bTlJUmpsWUhSMWI2eGw5cWk0b3FNMGNYYlVzRDdKK2tjbDFMWWtOK1lNbVIrWVZDZFc0a3ZyL3oxVHVMK0RsRmFlaXMwOVlSWWFvTDZTS09sK2FrUXBNbkM1ajc0UHZSUFkzRkxpQXFqUzE3ODhRS0VISmk=