apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: analytics-service
type: Opaque
data:
   AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMTIzOTQ1MzE0OTQ4L21pbmhhZmlsYQ==
   AWS_REGION: dXMtZWFzdC0x
   AWS_ACCESS_KEY_ID: QVNJQVJaVzVYTktDSERDSzM1WTY=
   AWS_SECRET_ACCESS_KEY: dHJmODNoUCtJRTVuSDcrd2FnSDA0MUh0RXU1anB3eDdReEdZZUlQaQ==
   AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVFY2FDWFZ6TFhkbGMzUXRNaUpITUVVQ0lFUk85dlo4cm5vbmlmeVlwQWRoYUFlalhFTjcveG92bExGRy9CSHVxa0VxQWlFQXVOM0RuL3d2WFBGMWlVWVZoVEg0Q242TEd6dGNBUTNjVVJlazYzVEhhWFlxdEFJSUVCQUFHZ3d4TWpNNU5EVXpNVFE1TkRnaURBSUtMbGJ0M3FxNnJSRDZmeXFSQXZrRjZTLy9FemZPMTRTTFpBNGlWZHBMTFF5YmhveDFyWkdCUFovSVhjclJxRmtyRzZzUlMwTDdNN3AvYWxYQTR5R0NNWUhTR0dGOVJXcUNUYUIycjJRbSthb2N2MGh2QjNPcjg1bStDa2xTMDJ1TVVHSVF2R2w5aVBJU2JmSS9uZEFBcGdlNmFab0Jsa05FdnJNcmJraFFwTitDMFFmTEhHdk9PSXpPWG0zQzF2TlBNcStmd0VWeldHV01ENWZkYlF3QjBrKzU4UGtWb0d2UGZFRzJqS2Y5TEZ5eitmYmp0VmNmWEMzSm5QU2swMlVBelpvQ2U5V3BOVFF5Y3MxSlFpK3NsZC9rbVpSOHkyUW1UVzZJMzZpUnhpODlzTmduRm9EdHExbUx5UTN6N2ZQaUcrVkV0dXRHRzZPOUx3aFowRnpoUU1MRnpXQkdmWUdtTTRSRDErdkV1bnRFT1oyek9LL2xwWlNjSlNOU2pqQ0luYjdRQmpxZEFmVHQ4SCsvVnVlNEwycEFXaDdGUmF1eTNnZGRJVldraUR6RU0zdmFsNFlCM1RJUXVqQ0Njc1hwdGN4dnFneGl3THdCcEVGaFp6TUp4enI3UlV6YVp4MkltY3YzTDFZaWM1TE41RzhIR2JuMXRJNjR0ZmsrMW5wV0NNSVBySkVUMnlJejBoR0NPc0NHbGVQTTFJT2s1c2IvQ3p2d01kL2psSDdFSGs0M3BYMm5pb01BeVc3SEdlcVJ2dnZKTGMwSVdmdHpHckc5NkN4NENBaGNvMzA9
   AWS_DYNAMODB_TABLE: VG9nZ2xlTWFzdGVyQW5hbHl0aWNz