apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: analytics-service
type: Opaque
data:
   AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vNDc4MDc5MTk3MzU5L21pbmhhZmlsYQ==
   AWS_REGION: dXMtZWFzdC0x
   AWS_ACCESS_KEY_ID: QVNJQVc2VDU1VUNYVlRBV09GWEU=
   AWS_SECRET_ACCESS_KEY: bEtJVkJ4T1NLaTUxWXpVTEdmMGRIMjBYN3psU3FTMkxEN2QzUjA3cw==
   AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVMNy8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpITUVVQ0lDc1I1eVN6bmY2cGlTY1NPRm5FU2c4V0pBaWV0V29NU3pNY2ZyekdPQmIyQWlFQStiaU9vWWdSUUFNOHJqOTVzN1MrZHVNTDQzdEgwRDFPTy9QTy84SDBERGdxdXdJSWgvLy8vLy8vLy8vL0FSQUNHZ3cwTnpnd056a3hPVGN6TlRraURGK1l4dU56L01xOXdBSVlZeXFQQW5oOEVLVG9hT0pmOFBTdGl6UDJvMFZRdUNJUkJPbFBwbHVTdXNmajBJNk9rc3ZZcTM4UXVGNFZuc09UMGNqNjVlTzFVS2VDWmdmaHBPQ1BtZ296Mm05eVViSVNueGE3UTB5alBhbUhYLzB4dUZKZlUydnd2VnBEam8rd0Q4NXVsTithTThDK0R5NFpSZGQ1d21STDBobVNMalI1SzVtVUlhOVk3cjhhV3dVWWdxbDloU0hYb3YvNW9WU1NwTXgwMUNQZWN4TjNJRVFTd2xvT0NqeUxZcHRjaHNaUmlIRzlXOXZBY0swL3VUc3phT05YaG1SNktvaGlFNUhqb3ZnYlRlNkVmSUhpZ2xWYmlWYVFXZC9JM3E3czhiVjlTeHVQcmVkb2s2WFhlcDBneThFZXU1QnNKd2RKQkRIbjZhRlp2OTZXQitxK0VNLzQrTFNVOVA3VHlFQkpWT2d6d0ZrUjB2SjNjWU5CKy9nd2o2YlkwQVk2blFFd3RXTzdNRk14Vk1vbVJ2MEJ1dlZUc0dZaDIxTEVIdnUrK0VQOEJwT0FNUFZZSVl6TTdEd2NlZXFTY1VpSnpjdk83dURvVVhsdzJtTzZBL0pvRElvK0RmTnpCdDM5YXZ3Z0NVWHo3K2o4NUVIYlFWNGdsU1pIUDhtOXpPeTVHQURHUGhnSDBlYlpRL3ZqQXVPalZxRDZFL3FUZXZ2Y0I4ZkYvcUpISDVZd1RIdS9nU1FOSUU1TmYzaG5oR0V5YjFDMG8rb1dNYTNwRmZtVmlpSEc=
   AWS_DYNAMODB_TABLE: VG9nZ2xlTWFzdGVyQW5hbHl0aWNz