apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: auth-service
  labels:
    app: auth-service
data:
  DATABASE_URL: "postgres://dbadmin:5g4%24qY21X%5Du%23r7@authdb.cvwomoowc2qc.us-east-1.rds.amazonaws.com:5432/auth_db"
