apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: auth-service
type: Opaque
data:
  MASTER_KEY: ${{ secrets.Master_key }}
  POSTGRES_USER: ${{ secrets.auth_db_User }}
  POSTGRES_PASSWORD: ${{ secrets.auth_db_Pass }}
  POSTGRES_DB: ${{ secrets.auth_db }}
