apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-configmap
  namespace: targeting-service
  labels:
    app: targeting-service
data:
  DATABASE_URL: ${{ secrets.TARGETING_DB_URL }}
  AUTH_SERVICE_URL: ${{ secrets.AUTH_URL }}
