apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-configmap
  namespace: targeting-service
  labels:
    app: targeting-service
data:
  DATABASE_URL: "postgres://dbadmin:u1sgDE7FBW09@targetingdb.cvwomoowc2qc.us-east-1.rds.amazonaws.com:5432/targetingdb"
  AUTH_SERVICE_URL: "http://auth-service-clusterip.auth-service.svc.cluster.local:8001"
