apiVersion: v1
kind: Secret
metadata:
  name: targeting-secret
  namespace: targeting-service
type: Opaque
data:
  POSTGRES_USER: ${{ secrets.TARGETING_DB_USER }}
  POSTGRES_PASSWORD: ${{ secrets.TARGETING_DB_PASS }}
  POSTGRES_DB: ${{ secrets.TARGETING_DB }}
