apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-configmap
  namespace: flag-service
  labels:
    app: flag-service
data:
  AUTH_SERVICE_URL: "http://auth-service-clusterip.auth-service.svc.cluster.local:8001"
  DATABASE_URL: "postgres://dbadmin:2%IVLq4im$8C@flagsdb.cvwomoowc2qc.us-east-1.rds.amazonaws.com:5432/postgres"