apiVersion: v1
kind: Secret
metadata:
  name: flag-secret
  namespace: flag-service
type: Opaque
data:
  POSTGRES_USER: ${{ secrets.FLAG_DB_USER }}
  POSTGRES_PASSWORD: ${{ secrets.FLAG_DB_PASS }}
  POSTGRES_DB: ${{ secrets.FLAG_DB }}
