name: CI evaluation-service
# add comment
on:
  push:
    branches: [ "main" ]
    paths:
      - 'evaluation-service/**'
jobs:
  build-test:
    name: Build & Unit Test
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./evaluation-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go Application
        run: go build -v ./...

      - name: Run Unit Tests
        continue-on-error: true
        run: go test -v ./...

  lint:
    name: Linting
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./evaluation-service
        
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Analysing the code with golangci-lint
        uses: golangci/golangci-lint-action@v6
        continue-on-error: true
        with:
          version: v1.57.2
          working-directory: ./evaluation-service

  Scan-de-Seguranca-SCA:
    name: Scan-de-Seguranca (SCA)
    runs-on: self-hosted
    needs: lint

    defaults:
      run:
        working-directory: ./evaluation-service
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Software Composition Analysis - Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: './evaluation-service'
          vuln-type: library
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: 0

  Scan-de-Seguranca-SAST:
    name: Scan-de-Seguranca (SAST)
    runs-on: self-hosted
    needs: lint
    defaults:
      run:
        working-directory: ./evaluation-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=CITech03
            -Dsonar.organization=danilorferraz
            -Dsonar.sources=./evaluation-service

  Build-Push-Docker-Image:
    name: Build & Push Docker Image
    runs-on: self-hosted
    needs: [Scan-de-Seguranca-SCA, Scan-de-Seguranca-SAST]
    defaults:
      run:
        working-directory: ./evaluation-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Adicionando as credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construindo imagem Docker
        run: |
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t ${{ steps.login-ecr.outputs.registry }}/evaluation-service:$COMMIT_HASH .
          
          # Salvando as variáveis para usar nos próximos passos
          echo "IMAGE_TAG=$COMMIT_HASH" >> $GITHUB_ENV
          echo "REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Container Image Scan - Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/evaluation-service:${{ env.IMAGE_TAG }}
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: 0

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ env.REGISTRY }}/evaluation-service:${{ env.IMAGE_TAG }}

      - name: Update GitOps Repo
        run: |
          git clone https://${{ secrets.GITOPS_PAT }}@github.com/${{ github.repository }}.git gitops-repo
          cd gitops-repo/Kubernetes/evaluation-service
          
          sed -i "s|image: .*|image: ${{ env.REGISTRY }}/evaluation-service:${{ env.IMAGE_TAG }}|g" deployment.yaml
          
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "chore(gitops): atualiza imagem do evaluation-service para ${{ env.IMAGE_TAG }}"
          git push origin main
