name: Terraform deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Adicionandos as credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./Terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./Terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./Terraform
        run: terraform apply -auto-approve

      - name: Configurar acesso kubectl no EKS
        run: |
          aws eks update-kubeconfig --name clusterpos --region us-east-1
      
      - name: instalar ArgoCD (server-side)
        run: |
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
          
          kubectl apply \
            --server-side \
            --force-conflicts \
            -n argocd \
            -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

          kubectl patch svc argocd-server -n argocd \