name: Terraform deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Adicionandos as credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./Terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./Terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./Terraform
        run: terraform apply -auto-approve

      - name: Configurar acesso kubectl no EKS
        run: |
          aws eks update-kubeconfig --name clusterpos --region us-east-1
          
          # Pega o ARN da role/user atual do GitHub Actions
          CALLER_ARN=$(aws sts get-caller-identity --query Arn --output text)
          
          # Adiciona como admin no cluster
          aws eks create-access-entry \
            --cluster-name clusterpos \
            --principal-arn $CALLER_ARN \
            --region us-east-1 || true

          aws eks associate-access-policy \
            --cluster-name clusterpos \
            --principal-arn $CALLER_ARN \
            --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy \
            --access-scope type=cluster \
            --region us-east-1 || true

      - name: Instalado ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd

