name: Run All Pipelines

on:
  workflow_dispatch:

jobs:
  trigger-auth-service:
    name: Trigger auth-service Pipeline
    runs-on: self-hosted
    steps:
      - name: Trigger auth-service-pipeline
        uses: ./.github/workflows/auth-service-pipeline.yaml

  trigger-analytics-service:
    name: Trigger analytics-service Pipeline
    runs-on: self-hosted
    steps:
      - name: Trigger CIanalytics-service
        uses: ./.github/workflows/CIanalytics-service.yaml

  trigger-evaluation-service:
    name: Trigger evaluation-service Pipeline
    runs-on: self-hosted
    steps:
      - name: Trigger evaluation-ci
        uses: ./.github/workflows/evaluation-ci.yaml

  trigger-flag-service:
    name: Trigger flag-service Pipeline
    runs-on: self-hosted
    steps:
      - name: Trigger flagserviceCI
        uses: ./.github/workflows/flagserviceCI.yaml

  trigger-targeting-service:
    name: Trigger targeting-service Pipeline
    runs-on: self-hosted
    steps:
      - name: Trigger targetingserviceCI
        uses: ./.github/workflows/targetingserviceCI.yaml
