# Reusable Workflow for security checks
# Este workflow é chamado por diferentes serviços
name: security-checks
on:
  workflow_dispatch:
    inputs:
      service-name:
        description: 'Nome do serviço/pasta'
        required: false
        default: 'targeting-service'
  workflow_call:
    inputs:
      service-name:
        description: 'Nome do serviço/pasta'
        required: false
        type: string
        default: 'targeting-service'

jobs:

  SAST:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.service-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bandit
        run: |
          pip install bandit --break-system-packages

      - name: Run bandit
        run: |
          bandit -r . --severity-level high

  Trivy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.service-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
