# Workflow for security checks
# add comment
name: targeting-service security-checks
on:
  workflow_dispatch:
  workflow_call:

jobs:

  SAST:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./targeting-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bandit
        run: |
          pip install bandit --break-system-packages

      - name: Run bandit
        run: |
          /home/douglas/.local/bin/bandit -r . --severity-level high

  Trivy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./targeting-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
